apply plugin: 'com.android.library'

def expoModulesCorePlugin = new File(
  project(':expo-modules-core').projectDir.absolutePath,
  'ExpoModulesCorePlugin.gradle'
)
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()

group = 'expo.modules.pbkdf2'
version = '1.0.0'

android {
  namespace 'expo.modules.pbkdf2'
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}
