apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

group = 'expo.modules.pbkdf2'
version = '1.0.0'

android {
  compileSdkVersion safeExtGet("compileSdkVersion", 35)
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    targetSdkVersion safeExtGet("targetSdkVersion", 35)
  }
  kotlinOptions {
    jvmTarget = '17'
  }
  namespace 'expo.modules.pbkdf2'
  publishing {
    singleVariant('release') {
      withSourcesJar()
    }
  }
}

repositories {
  mavenCentral()
  google()
}

def safeExtGet(prop, fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${safeExtGet('kotlinVersion', '1.9.25')}"
}
